dominant-strategies/go-quai

- cmd/devp2p/README.md
- cmd/devp2p/internal/ethtest/helpers.go
- cmd/devp2p/internal/ethtest/suite.go
- cmd/devp2p/internal/ethtest/suite_test.go
- cmd/devp2p/internal/ethtest/transaction.go
- cmd/devp2p/internal/ethtest/types.go
- cmd/devp2p/rlpxcmd.go
- cmd/utils/flags.go
- docs/postmortems/2021-08-22-split-postmortem.md
- eth/downloader/downloader.go
- eth/downloader/downloader_test.go
- eth/downloader/peer.go
- eth/handler_eth_test.go
- eth/peerset.go
- eth/protocols/eth/handler.go
- eth/protocols/eth/handler_test.go
- eth/protocols/eth/handshake_test.go
- eth/protocols/eth/peer.go
- eth/protocols/eth/protocol.go
- eth/protocols/eth/protocol_test.go
- eth/protocols/snap/handler.go
- eth/protocols/snap/protocol.go
- eth/sync_test.go
- les/client_handler.go
- les/downloader/downloader.go
- les/downloader/downloader_test.go
- les/downloader/peer.go
- p2p/discover/table.go
Moved from eth66 -> quai66 protocol naming and versioning. This is a breaking peering change. Will need to be rolled out post Stone Age testnet completion.
> Updated protocol version

- consensus/ethash/consensus.go
- core/blockchain.go
- core/state_processor.go
- eth/downloader/downloader.go
- eth/downloader/queue.go
- eth/fetcher/block_fetcher.go
- eth/handler.go
- eth/protocols/eth/broadcast.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/peer.go
- eth/sync.go
Updated several items:
- Proper starting header when passing ext blocks since we are not given a candidate
- Updated broadcast handler to pass external blocks
- Revised logging
> Updated peering for external block passing

- core/types/transaction.go
- core/types/transaction_signing.go
The issue was with the processing of external blocks, the `region-1`  `eip155signer` was trying to get the `from`
address of the tx from `zone-1-1`  and it was failing as expected.
There are 2 more places where the mulId is used in the repo, will see the significance of the change on that before we merge this in. 
To understand the implication of the EIP155 and its use, please go through the doc below
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
> Fixed the invalid signature issues while processing External Blocks

- core/rawdb/accessors_chain.go
- core/rawdb/schema.go
Added unique key to external headers so they do not conflict with operations on local headers.
> Fixed ReadAllHashes improperly removing external blocks

- core/chain_fork_tests.go
- core/chain_makers.go
@BryceAgent & @williamdboyd this PR attempts to establish the framework for fork choice tests. I expect your work to extend this framework. Notice I have not implemented several of the key functions, those remain to be implemented by all three of us.
@BryceAgent I left review comments in your PR to this effect, but please move any logic not related to testing chain makers our of `chain_makers_test.go`. Logic necessary to implement fork choice tests should go in the new `fork_choice_tests.go` file instead. **Your block generator should become the implementation of `GenerateNetworkBlocks()`. Please make be sure your implementation satisfies that requirement.**
@williamdboyd the tests you are writing should become new copies of the `ForkChoiceTest_Slide00()` function I give below. e.g. when …
> Boiler plate & test framework for fork choice tests

- core/blockchain.go
core/blockchain.go: reverted the reorgTwistToCommonAncestor to use the uncle feed and send the last num==nil block
> core/blockchain.go: reverted the reorgTwistToCommonAncestor

- eth/handler.go
- p2p/discover/table.go
This PR disables any peer diversity requirements in the peering client, and allows our node to promiscuously peer to anyone. This is a development feature only, and should not be released officially.
> DEV ONLY: made modifications to allow us to dev without dropping peers.

- consensus/blake3pow/consensus.go
- consensus/clique/clique.go
- consensus/consensus.go
Adds a method to check if a block header is coincident with the dominant chain (if exists)
> Add IsDomCoincident() method to Blake3pow

- cmd/utils/flags.go
- common/types.go
This solves a few issues. First, RLP encoding an array with nil values could result in 0's, when what we really want is empty/non-existant elements. Alternatives involved changing nil to 0 and requiring everywhere which used Location to translate between 1/0 and handle cases where 0 should not be allowed. Using dynamic arrays solves all of those complexities.
> Use dynamic size array for Location

- core/types/block.go
The whole point with accessor methods was to remove the dangling
pointer references and shared memory writes.
This bug was introduced at 5053d7e.
> BugFix: Should not set a pointer in the setter methods

- p2p/discover/common.go
- p2p/discover/v4_lookup_test.go
- p2p/discover/v4_udp.go
- p2p/discover/v4_udp_test.go
- p2p/discover/v4wire/v4wire.go
- p2p/discover/v4wire/v4wire_test.go
- p2p/discover/v5_udp.go
- p2p/discover/v5_udp_test.go
- p2p/server.go
This reverts commit 251f715fbb43cfd513677ebdd3270ab388531256.
Commit 251f removed the v4wire which resulted in node not being able to peer with the bootnode. So reverting it back.
> Revert "Removed v4wire"

- Makefile
It took me a while to understand what was going on here. I finally realized that the issue was as follows:
`pkill` was actually shutting down the makefile process. I misdiagnosed this quite a few times before realizing that. 
Honestly, I may still be misunderstanding the issue. I had a pretty hard time finding good guides/docs on makefiles as a whole. I read through [one](https://www.grymoire.com/Unix/Make.html#Conditional_execution_in_Makefiles) and [two](https://web.mit.edu/gnu/doc/html/make_4.html) resources and just couldn't find a good explanation. 
What I can say is that the makefile was terminating early bc of the `pkill` and now it is no longer doing that. 
So [this unix stackexchange post](https://unix.stackexchange.com/questions/448880/makefile-kill-a-process-if-it-is-running) …
> fix issue with makefile

- quaistats/quaistats.go
This is a very small change that simply makes the pending report more similar to the others for code-parity with `quai-stats-backend` . 
Dependent on: https://github.com/dominant-strategies/quai-stats-backend/pull/9 
Linear: https://linear.app/quai-network/issue/FS-64/implement-case-pending-in-servergo-for-the-stats-backend
> bring pending report inline with others

- core/core.go
- core/headerchain.go
- core/slice.go
- core/types/block.go
- eth/api_backend.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- quaiclient/quaiclient.go
The original idea of caching pending manifests was flawed. This PR reverts that commit and implements a better solution: when `InsertChain()` is called for a block whose manifest we don't know, we ask our sub for the manifest and rewrite the block body with the correct manifest.
> Revert pendingManifest cache and ask sub for manifest

- cmd/utils/flags.go
- quaistats/quaistats.go
The primary question I have for reviewers is what the thoughts are the on the https://github.com/dominant-strategies/go-quai/pull/466/commits/322a70d3878b32889e1b1c8bc30e2c4800c46ae8 commit. 
I added that because I wanted to marshal the location array, but did not want to get a [base-64 encoded string](https://pkg.go.dev/encoding/json#Marshal) that would have to be later de-encoded before insertion into the postgres db for the stats-manager. 
Stats-Backend PR dependency: https://github.com/dominant-strategies/quai-stats-backend/pull/10
Linear: https://linear.app/quai-network/issue/FS-173/add-chain-to-block
> add the chain to block stats reporting

- common/types.go
- core/block_validator.go
- core/headerchain.go
- core/slice.go
- core/state_processor.go
- core/state_transition.go
- core/types/receipt.go
- core/vm/evm.go
- core/vm/instructions.go
- core/worker.go
This PR depends on https://github.com/dominant-strategies/go-quai/pull/463. Only the last 3 commits are pertinent to this feature. I will remove the PR from draft state once https://github.com/dominant-strategies/go-quai/pull/463 merges.
This PR implements the ETX rollup. Future work will broadcast block bodies (with the ETX rollups) through a domclient for routing to the destination chain(s)
> Emit ETXs from EVM and rollup into coincident blocks

- common/types.go
- core/bodydb.go
- core/core.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/schema.go
- core/rawdb/table.go
- core/slice.go
- core/state_processor.go
- core/types/etx_set.go
- core/types/external_tx.go
- core/types/internal_tx.go
- core/types/transaction.go
- eth/api_backend.go
- ethdb/database.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- quaiclient/quaiclient.go
This patch implements logic relating to ETX collection, relaying, and referencing within a slice. Namely:
* Send newly emitted ETXs to our dom (rolling up when appropriate)
* Use subordinate manifest to collect the 'spendable set' of ETXs
* Share the correct set of referencable ETXs with our subordinates for inclusion in blocks
Note: this effectively saturates a full node with the necessary pending ETX data. To support running just a slice, we will need to implement broadcast & propagation logic to ensure these pending ETXs make it to those nodes.
> Add domclient route to relay ETXs up through slice

- common/types.go
- core/slice.go
Using just 'l' as a shortname for location was causing confusion (mistaken for `1`, unable to search for instances of 'l', etc). I've decided to use the slightly longer `loc` to make the code more readable & alleviate those challenges.
> Use more descriptive names in Location methods

- core/state_processor.go
- core/state_processor_test.go
- core/vm/evm.go
- core/vm/instructions.go
ETX nonce is now the sender or contract nonce and zero address balance is reset after inbound ETX processing (residual is no longer stored)
> ETX nonce modification and zero address balance reset

- eth/sync.go
Minimum number of peers to start syncing is changed from 5 to 1. An issue has been created
https://github.com/dominant-strategies/go-quai/issues/537 to document this change.
> Changed min peers to one

- README.md
Removed many references to geth, and replaced instructions for running go-quai. Including:
- Discord, goreportcard, and go module reference
- Make commands for building mainnet
- Configuration changes for building testnet
- Contribution guidelines/details
- License carryover from geth (GPLv3)
- Commented out sections about configuration
> README refactoring and updates.

- core/types/gen_header_json.go
- internal/quaiapi/quai_api.go
- Implements GetHeaderByNumber in Quai namespace.
- Fix for https://github.com/dominant-strategies/go-quai/issues/639.
> Implemented GetHeaderByNumber, and removed problematic checking of block timestamp

- core/vm/interpreter.go
Fixes https://github.com/dominant-strategies/go-quai/issues/650 except for dependency mapping
> Address out-of-scope error is properly returned from EVM and execution halts

- common/timedcache/timedcache.go
- core/core.go
This PR moves the timedcache to its own module, adds mutexes (and fixing some errors related to this), and implements an eviction callback mechanism needed for future work.
> Timedcache improvements

- cmd/go-quai/config.go
- core/state_processor_test.go
- core/vm/contracts.go
- core/vm/evm.go
Generated 13 addresses for each precompile (117 total) that are in-scope respective to each chain. Based on the node's location, an address will be chosen for a precompile that fits the scope. Fixes https://github.com/dominant-strategies/go-quai/issues/507
Note: addresses 1-9 are supported for Call/StaticCall operations, but are not strictly in-scope (except for Prime). Rather, the address is translated to its respective in-scope address during the Call operation. In the Prime case, addresses 1-9 are in-scope and map directly to the original precompiles.
> Fixed precompiles

- README.md
Helps users find where their logs are stored, which is the first thing they'll want to keep an eye on to make sure everything is running correctly.
> Specify logs directory in README

- Makefile
- network.env.dist
@Djadih has inspired me to also make modifications to the Makefile. This PR now takes in a required `VERBOSITY` network.env variable.
> Add verbosity to network.env

- Makefile
Makefile -> Added the --nat flag when BOOTNODE=true to prevent loopback errors in the ENR
> Makefile -> Added --nat flag when BOOTNODE=true to prevent loopback error in ENR

- core/worker.go
Resolves https://github.com/dominant-strategies/go-quai/issues/723
> bugfix: Skip manifest & rollup calc in Prime

- core/rawdb/accessors_chain.go
> bugfix: EtxSet RLP encode was encoding the wrapper

- consensus/blake3pow/consensus.go
- consensus/blake3pow/sealer.go
- consensus/consensus.go
- core/types/block.go
- core/worker.go
- params/config.go
This change was desired so that miners do not have to hash the entire
header (which is quite large) for every solution. This makes mining more
efficient AND simplifies logic for GPU/ASIC implementations.
> Modify header hash to instead hash SealHash+nonce

- .github/workflows/lint-on-pr.yml
This github action uses https://golangci-lint.run/
Maybe we are interested in installing this locally and running it in pre-commit hooks as well?
> added a github action to lint PR's

- cmd/utils/flags.go
- common/address.go
- common/internal_address.go
- core/core.go
- core/tx_journal.go
- core/tx_noncer.go
- core/tx_pool.go
- core/types/transaction.go
- core/vm/evm.go
- core/worker.go
- eth/api_backend.go
- eth/backend.go
- eth/handler.go
- internal/quaiapi/api.go
- internal/quaiapi/backend.go
Tx pool now uses InternalAddress. Worker uses generic address bytes type. In addition, fixed a bug where the nonce wouldn't be incremented in certain tx fails.
> Fix one tx per block

- eth/downloader/downloader.go
After this change, we are able to sync 20,000 zone blocks without a single peer drop
> bugfix: Increase the timeout for skeleton fetch

- internal/quaiapi/api.go
- internal/quaiapi/transaction_args.go
toTransaction() and ToTransaction() are not used, and coerce every transaction to an Internal tx, so they should be removed. Fixes https://github.com/dominant-strategies/go-quai/issues/583
> Remove toTransaction()

- consensus/misc/eip1559.go
- params/protocol_params.go
This is just for testing. Should be removed in actual testnet
> Added a ceiling to the basefee, configured in protocol_params.go

- consensus/misc/rewards.go
We need to increase the block reward to send more transactions. After mining 50 zone blocks with these changes, my balance was ~92.5, which is slightly less than 2 per zone block.
With https://github.com/dominant-strategies/go-quai/pull/770 we introduced a base fee ceiling of 1 gwei (10^9) per unit of gas. A normal 21k gas transaction will thus cost at least 0.000021 plus the amount sent. This means that the block reward from each zone block will allow us to send anywhere between 10k-100k transactions depending on the amount sent per transaction (and the miner tip, which can be set to 1). 
Note that if we want to send transactions to addresses who then send transactions to other addresses and so on, the amount sent initially would need to be on the order of …
> Increase block reward by a factor of 1000

- core/slice.go
> bugfix: NewGenesisPh should only relay to existing subclients

- core/evm.go
- core/vm/evm.go
- core/vm/instructions.go
ETX miner tip per unit gas must now be at least double the originating transaction miner tip per unit gas. In addition, I added fee validation checks to opETX which was left out before.
> Fix etx validation

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-sandbox.yml
Great news! We're ditching the auto pre-release rev for every feature branch merged, and switching to a manual process instead. We heard you loud and clear – rebasing was getting annoying!
Perks of the change:
1. **No more rebasing nightmares**: Merge multiple PRs without having to deal with version rev'ing each time.
2. **Secrets are safe**: Manual actions have access to secrets, so the fork problem of #764 is solved.
3. **Flexibility FTW**: You decide when a pre-release rev is needed. More control, less hassle.
> Say Goodbye to Rebasing Hassles

- hooks/install-hooks.sh
- hooks/pre-commit
I've added a nifty install-hook.sh script and a pre-commit hook to our project. This is going to help us keep our code clean and catch potential issues before they even hit the PR stage.
Here's what's included in this PR:
1. `install-hook.sh`: This script checks if golangci-lint is installed, installs it if needed, and sets up the pre-commit hook.
2. Pre-commit hook: Before each commit, this hook will automatically run `golangci-lint` to lint our Go code and go test to run our test suite.
To get started, just run `./install-hook.sh` once, and you're all set!
Let me know if you have any questions or suggestions. Happy coding
> Add golangci-lint and pre-commit hook to automate linting and testing

- core/headerchain.go
Eliminates the need to mess with print statements to figure out what the new genesis hash is.
Also alerts the user with the full hash print of what was expected vs given.
> Display error upon genesis hash mismatch, and list the hashes

- Makefile
- cmd/go-quai/main.go
- cmd/go-quai/usage.go
- cmd/utils/flags.go
- core/genesis.go
- network.env.dist
In order to properly segregate networks, the genesis block nonce is now specified in network.env for all networks other than Colosseum (public testnet). If you do not add the correct nonce for the genesis block for the respective network your node will not run.
> Move genesis nonce to network.env

- consensus/misc/eip1559_test.go
- core/state_processor_test.go
- core/state_transition.go
- core/tx_pool.go
- core/vm/contracts.go
- core/vm/contracts_test.go
- core/vm/eips.go
- core/vm/gas_table.go
- core/vm/gas_table_test.go
- core/vm/jump_table.go
- core/vm/operations_acl.go
- core/vm/runtime/runtime.go
- params/config.go
- params/protocol_params.go
- tests/block_test.go
- tests/init.go
- tests/state_test.go
- tests/transaction_test_util.go
> Cleanup Istanbul

- Makefile
- cmd/go-quai/main.go
- cmd/go-quai/usage.go
- cmd/utils/flags.go
- cmd/utils/flags_legacy.go
- eth/api.go
- eth/api_backend.go
- eth/backend.go
- network.env.dist
Removes unused references to mining threads in the network.env and the makefile. Removes mining functionality from the node in favor of using cpu and gpu miner.
> Miner and thread removal

- Makefile
Make run-slice has been broken since we removed state from Prime and Region. This allows run-slice to work again.
> Remove miner coinbase from Prime and Region

- Makefile
- cmd/go-quai/main.go
- cmd/utils/flags.go
- core/core.go
- core/headerchain.go
- core/types/block.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/handler.go
- eth/peerset.go
- eth/protocols/eth/handshake.go
- eth/protocols/eth/peer.go
- eth/protocols/eth/protocol.go
- network.env.dist
> Petx caching in Doms and Peer Location bucketing

- network.env.dist
Verbosity needs to be set to 4 (info level) to gain useful information about the progress of the node. The default verbosity just shows leveldb warnings that make it seem like the node isn't running.
> Set default verbosity to info level

- Makefile
- cmd/go-quai/main.go
- cmd/utils/flags.go
- log/logger.go
- network.env.dist
This helps when looking at logs in non TTY environments such as GCP log viewer or vim.
> Add showcolors flag to enable/disable colored log prints for non-TTYs

- core/headerchain.go
> bugfix: only stop the state processor in zones

- core/types/transaction.go
- core/types/transaction_signing.go
- internal/quaiapi/api.go
We no longer encode the chain ID into the v-value of the transaction signature (neither does Ethereum) and therefore checking if the transaction is replay-protected via the v-value is unnecessary. Instead, we have the chain ID in the transaction struct and it is signed along with the rest of the transaction data.
> Bugfix: GetTransactionByHash API Encoding

- consensus/blake3pow/consensus.go
- core/block_validator.go
- core/bloom_indexer.go
- core/chain_indexer.go
- core/error.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/schema.go
- core/slice.go
- core/state_processor.go
- core/types/block.go
- core/types/gen_header_json.go
- eth/api_backend.go
- eth/filters/bench_test.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- internal/quaiapi/api.go
- params/config.go
- tests/block_test_util.go
> Remove Bloom from Header

- eth/downloader/queue.go
- eth/protocols/eth/handlers.go
Removed the unnessesary number checks in the queue, and in the handlers for the get header by number request was sending an extra genesis header which is not required.
Also simplified the logic of accepting the chain of headers in the queue
> bugfix: Fixed the downloader issue and extra genesis header response

- cmd/utils/flags.go
- core/genesis.go
- core/worker.go
- eth/ethconfig/config.go
- params/config.go
- params/protocol_params.go
Previously the gas adjustment was being done using arbitrary code which I couldn't track from Geth. And the variables were being used in a wrong way.
PROBLEM: To be specific, genesis gas limit was set to the min gas limit and Parent gas limit was given as an input to the CalcGasLimit function. This meant that the gas limit would never adjust and it will always stay the same as the genesis gas limit set in the genesis block.
SOLUTION: Gas limit should adjust based on the usage, and by default a spike in the gas limit shouldn't be allowed This Commit does exactly that.
CalcGasLimit takes parent gas limit and the desired gas limit and returns the gas limit after adjustment, either adding/subtracting a fixed proportion of the parent gas limit to the parent gas limit.
If the percentage of gas …
> GasLimit adjustment logic updated and network specific gas ceil is used

- internal/quaiapi/quai_api.go
Fixes `block not found` error while doing `quai_estimateGas`
Example API call:
```
{
"id": 1,
"jsonrpc": "2.0",
"method": "quai_estimateGas",
"params": [{"from": "0x04a3e45aa16163F2663015b6695894D918866d19","to": "0x1930e0b28d3766e895df661de871a9b8ab70a4da","gas": "0x76c0","gasPrice": "0x9184e72a000","value": "0x9184e72a","data": "0xd46e8dd67c5d32be8d46e8dd67c5d32be8058bb8eb970870f072445675058bb8eb970870f072445675"}]
}
```
> fix: estimate gas pendingBlock to latestBlock

- consensus/progpow/algorithm.go
- consensus/progpow/algorithm_progpow.go
Need this to reduce reliance on zone coordination of the epoch and period number.
> Modify ProgPow to increase period and epoch length

- core/types/etx_set.go
- core/worker.go
- params/protocol_params.go
This fixes a bug, where the worker might build blocks which include inbound ETXs which _should_ have expired _on this block_. A lot of factors have to converge for this bug to trigger, but once it does, the worker (all workers) becomes unable to build on the latest block.
> Worker needs to prune expired ETXs before building blocks

- Makefile
- cmd/go-quai/main.go
- cmd/go-quai/usage.go
- cmd/utils/flags.go
- consensus/blake3pow/api.go
- consensus/blake3pow/blake3pow.go
- consensus/blake3pow/blake3pow_test.go
- consensus/blake3pow/consensus.go
- consensus/blake3pow/consensus_test.go
- consensus/blake3pow/poem.go
- consensus/blake3pow/sealer.go
- consensus/blake3pow/sealer_test.go
- consensus/consensus.go
- core/genesis.go
- core/headerchain.go
- core/types/block.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/handler.go
- network.env.dist
- params/bootnodes.go
- params/config.go
If in flags consensus.engine is set to "blake3", blake3 consensus engine is initialized in the backend instead of the progpow, but the progpow wil remain as the default
> Added the blake3 consensus engine back in

- consensus/progpow/algorithm.go
- core/core.go
- eth/api_backend.go
- eth/backend.go
- internal/quaiapi/api.go
- internal/quaiapi/backend.go
This PR fixes the debug_seedHash API to return the progpow seed hash of a block by number.
Referenced in https://github.com/dominant-strategies/go-quai/issues/627
> Fix SeedHash API

- core/state_processor.go
The returned error message includes the wrong etxlimit because the integer pointer isn't dereferenced.
> ETX limit error message should dereference pointer

- core/state_processor.go
> bugfix: Node crash if the etxEntry doesnt exist

- common/big.go
- consensus/blake3pow/consensus.go
- consensus/blake3pow/poem.go
- consensus/consensus.go
- consensus/progpow/consensus.go
- consensus/progpow/poem.go
- core/chain_makers.go
- core/core.go
- core/genesis.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/slice.go
- core/types/block.go
- core/types/gen_header_json.go
- core/worker.go
- eth/api_backend.go
- eth/downloader/downloader.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- quaiclient/quaiclient.go
CalcPrimeDifficultyThreshold calculates the difficulty that a block must meet to become a region block.  This function needs to have a controller so that the liveliness of the slices can balance even if the hash rate of the slice varies. This will also cause the production of the prime blocks to naturally diverge with time reducing the uncle rate.  The controller is built to adjust the number of zone blocks it takes to produce a prime block.  This is done based on the prior number of blocks to reach threshold which is than multiplied by the current difficulty to establish the threshold. The controller adjust the block threshold value and is a simple form of a bang-bang controller which is all that is needed to ensure liveliness of the slices in prime …
> Region and Prime blocks using Prime and Region Entropy Threshold 

- core/types/gen_receipt_json.go
- core/types/receipt.go
- core/types/receipt_test.go
- internal/quaiapi/api.go
> bugfix: Fixed the receipt encoding and decoding issue

- core/worker.go
> bugfix: fix the etx bug from the etx cache

- core/core.go
- core/headerchain.go
- core/slice.go
- core/types/transaction.go
- core/worker.go
> Revert the Etx sorting work

- core/slice.go
> bugfix: guard against the async state update if poem fails

- common/big.go
- consensus/blake3pow/consensus.go
- consensus/blake3pow/poem.go
- consensus/consensus.go
- consensus/progpow/consensus.go
- consensus/progpow/poem.go
- core/core.go
- core/genesis.go
- core/slice.go
- core/types/block.go
- core/types/gen_header_json.go
- core/worker.go
- eth/api_backend.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- params/protocol_params.go
- quaiclient/quaiclient.go
> Poem upgrade

- cmd/utils/flags.go
- core/core.go
- core/slice.go
- core/tx_pool.go
- core/worker.go
- eth/backend.go
- eth/downloader/downloader.go
- eth/downloader/queue.go
- eth/handler.go
- eth/sync.go
- network.env.dist
Commit explanations are in the git commit messages
> Sync fixes and append queue updates

- Makefile
- network.env.dist
> add no discover in Makefile

- Makefile
- README.md
> Remove run-slice as an option and replace run-all with just `run`

- core/core.go
- core/slice.go
> Bug fixes from garden testing

- core/core.go
- core/slice.go
- eth/api_backend.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- quaiclient/quaiclient.go
> bugfixes from the garden tests related to the slice logic

- consensus/blake3pow/poem.go
- consensus/progpow/poem.go
From simulations and rigorous testing we have understood that there is stable operating point on just using Stoichastic or using the threshold to determine Dom blocks in a Synchronous setting
To be able to handle the adverse network scenarios and testnet environment and malicious miners the correct solution is mixture of having threshold to counteract malicious miners getting lucky and having a increased difficulty threshold to find a dom block
> Dom blocks are decided on both theshold of entropy and higher difficulty threshold

- core/core.go
> Adding lock to reduce the memory pressure while synching

- README.md
Hi everyone,
You may remember me from PR #1089. Unfortunately, that PR had some issues which forced to create a new PR with the updated changes. I have included the recommended changes from @wizeguyy based on conversations on terminology.
Thanks!
> Updated README links & terminology

- cmd/utils/flags.go
- params/config.go
For the filter on the ForkId we need the location on the chainconfig
> Adding Location to the ChainConfig

- eth/fetcher/block_fetcher.go
> Drop peers who broadcast stale blocks

- common/math/integer.go
- core/core.go
> Print the appendQueue that is blocking you from syncing

- core/core.go
- core/headerchain.go
- core/slice.go
- eth/handler.go
- eth/handler_eth.go
- eth/peerset.go
- eth/protocols/eth/handler.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/peer.go
- eth/protocols/eth/protocol.go
> Removing the PendingEtx/Rollup Fetching

- eth/sync.go
> Removed the force sync cycle

- eth/fetcher/block_fetcher.go
This dropping of peer is preventing nodes from syncing. If people are mining stale blocks and nodes are syncing, other nodes will drop the node.
> Don't drop the peer if received a stale broadcast

- core/bodydb.go
- core/headerchain.go
Removed the Block writes from bc Append and also prevented the race condition with the block getting nil because of eviction from the cache
> bugfix: modified headersWithoutState array to work on copies of headers

- core/worker.go
- eth/downloader/queue.go
Also this fixes the bug with the CurrentInfo print check, previously we were checking if the header exists, but it should be header hash, because header is a pointer and is different everytime
> Supress noisy prints from the Logs

- core/headerchain.go
> Recovers header if hash is not found in DB on startup

- eth/handler_eth.go
> bugfix: remove the stale block classification in handlerBroadcast

- eth/protocols/eth/handler.go
Tested by running local node and forcing head to be nil. Warning was logged and code continued to execute
```
INFO   [10-24|16:06:56.926] WebSocket enabled                        url=ws://127.0.0.1:8611
INFO   [10-24|16:06:56.926] Stats daemon started
WARNING[10-24|16:06:56.926] chain.CurrentBlock() returned nil
WARNING[10-24|16:06:57.990] Error calculating directory sizes:
INFO   [10-24|16:06:58.711] Allocating genesis accounts              num=8160
INFO   [10-24|16:06:58.786] Commit new sealing work                  number=1 sealhash=0x70571b9875fc42310533c7b3d8e5c30946edc25b5869cfd8cbd31b01ad11beb3 uncles=0 txs=0 etxs=0 gas=0 fees=0 elapsed=89.656ms
INFO   [10-24|16:06:59.044] Port mapping found on                    Interface=UPNP IGDv2-IP2
```
> Adds nil check after chain.CurrentBlock()

- core/block_validator.go
- core/evm.go
- core/state_processor.go
Block to change timestamp in EVM is block 690000 across all zones.
> Bugfixes: EVM timestamp should use parent timestamp, remove unused emittedEtxs, fixed receipt ETX collection

- eth/backend.go
- quaiclient/ethclient/ethclient.go
- quaiclient/quaiclient.go
- rpc/client.go
> Still keep eth namespace support for filter API

- cmd/go-quai/config.go
- core/bodydb.go
- core/vm/contracts.go
- core/vm/evm.go
- core/vm/instructions.go
There are several issues with precompiles that are fixed in this PR.
1. StaticCall and DelegateCall returned out of scope errors on precompile addresses that are called before they are translated to in-scope addresses.
2. Precompile addresses generated by Solidity were not properly translated to in-scope precompiles
3. The precompiles were not properly initialized when the node starts up because the NodeLocation was empty.
> Bugfixes: No errors on precompile, proper translation, proper initialization

- core/vm/evm.go
- params/protocol_params.go
evm.Create() now grinds the proper address for a smart contract via Create2 if the user did not do so before sending the tx and charges the user accordingly based on how many iterations it took. The Create2 salt is a concatenation of the caller nonce and the for-loop iterator. The ensures that new contracts will always have different addresses.
Create also allows a user to grind their own address with the end of the contract bytecode before sending the tx if they choose - this does not cost any extra gas.
> Modify create opcode to grind address

- core/tx_pool.go
- internal/quaiapi/quai_api.go
And InternalToExternal Tx to must not be nil
Also, estimate gas for ExternalTx will return an error. Instead, the caller should estimate gas as an internal tx on the destination chain.
> Bugfix: Estimate Gas for InternalToExternal Tx

- p2p/node/api.go
- p2p/protocol/interface.go
- p2p/pubsubManager/gossipsub.go
- quai/interface.go
- quai/p2p_backend.go
These are stubs for validation of:
blocks
transactions
Anything that gets ValidationReject will not only not re-propagate to peers, but will also not be sent to consensus. Suggest quick validation of things without excessive processing.
> Propagation hooks

- cmd/utils/flags.go
Needs to be used by stratum to not duplicate the functionality
> Expose functions for WS and HTTP ports

- p2p/peerManager/peerManager.go
Our current method of identifying slices that are running doesn't work for all cases. Instead of doing the refactor and developing the logic this commit will get us through to 3x3.
> Assume heirarchy for some background tasks for now

- cmd/utils/flags.go
> bugfix: ensure SubUrls always use correct port numbers

- internal/quaiapi/api.go
- internal/quaiapi/quai_api.go
- quaiclient/ethclient/ethclient.go
RPC request with invalid address checksum:
```zsh
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"quai_getBalance","params":["0x007d73d8a49eeb85d32cf465507dd71d507100c1", "latest"],"id":1}' 127.0.0.1:9200
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"address has invalid checksum"}}
```
Try again with correct checksum:
```zsh
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"quai_getBalance","params":["0x007d73D8A49Eeb85D32Cf465507dD71d507100c1", "latest"],"id":1}' 127.0.0.1:9200
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```
> rpc: Enforce MixedcaseAddress with valid checksums on all methods

- quaistats/quaistats.go
Now sends transaction stats for multiple transaction types. Please coordinate with me when merging or redeploying with this commit because I will need to update the rest of the stats stack at the same type. Otherwise, no transaction stats until it is updated.
> stats for chi and external transactions

- p2p/node/peerManager/peerdb/counter_test.go
- p2p/node/peerManager/peerdb/datastore_test.go
- p2p/node/peerManager/peerdb/main_test.go
Set the overall coverage on peerdb module up to 83.3%
> P2p peerdb tests

- p2p/node/peerManager/peerManager.go
Resolves https://github.com/dominant-strategies/go-quai/issues/1744
> bugfix: always at least allocate empty peer map

- cmd/utils/hierarchical_coordinator.go
- consensus/blake3pow/consensus.go
- consensus/blake3pow/poem.go
- consensus/blake3pow/sealer.go
- consensus/consensus.go
- consensus/progpow/consensus.go
- consensus/progpow/poem.go
- consensus/progpow/sealer.go
- core/core.go
- core/events.go
- core/headerchain.go
- core/slice.go
- core/worker.go
- internal/quaiapi/backend.go
- internal/quaiapi/quai_api.go
- p2p/node/api.go
- p2p/node/pubsubManager/utils.go
- p2p/pb/proto_services.go
- params/protocol_params.go
- quai/api_backend.go
- quai/p2p_backend.go
- quaiclient/quaiclient.go
workshares are sub shares found in the process of producing a block. Including these sub share samples in the block makes the statistical convergence better. So in this PR, workshares have been added into the uncles list. The weight of the workshares is added into the parent entropy and also parent sub delta S. But a discount based on the reference depth and frequency of workshares is applied while adding the entropy of the workshare.
> Workshares are included and being able to mine

- consensus/blake3pow/consensus.go
- consensus/consensus.go
- consensus/progpow/consensus.go
- core/bodydb.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/types/wo.go
During the workshare/uncle verification we read the workobject with the transactions from the database but we only need to get the workshare information, and this was causing significant RAM usage at high TPS testing. This optimization completely removes that RAM usage by just reading the WorkShares along with the Header information
> Only Read the workobject with workshares during the verify uncles

- p2p/node/api.go
- p2p/node/peerManager/peerManager.go
- p2p/node/pubsubManager/gossipsub.go
resolves https://github.com/dominant-strategies/go-quai/issues/1756
> Go func recover

- p2p/node/streamManager/streamManager.go
This was requested to go in main to keep track of streamCache accesses. Tests are run at info level so that's where the print was set.
> View stream cache status

- common/common_metrics.go
- core/tx_pool.go
- metrics_config/grafana_metrics.json
- p2p/node/stats.go
Updated panels with 1m counters, reorganized dashboard, fixed previously broken numPeers metric.
Closes #1644
> Transaction metrics

- cmd/go-quai/start.go
- cmd/utils/cmd.go
- p2p/node/node.go
- params/version.go
Resolves: https://github.com/dominant-strategies/go-quai/issues/1290
Resolves: https://github.com/dominant-strategies/go-quai/issues/1892
> Version stuff

- .gitignore
- core/core.go
- core/genesis.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_test.go
- core/slice.go
- core/types/block.go
- core/types/wo.go
- core/worker.go
This Pr increase coverage on accessors_chain.go up to 49.7%
> Accessor methods tests

- core/evm.go
- core/genesis.go
- core/rawdb/accessors_chain.go
- core/state_processor.go
- core/types/wo.go
- core/worker.go
- params/config.go
- quai/gasprice/feehistory.go
Fixes https://github.com/dominant-strategies/go-quai/issues/1790
> Remove ExternalTransactions from QuaiTransactions and disable receipts from Qi ETXs

- core/core.go
- core/headerchain.go
- core/rawdb/accessors_chain.go
- core/rawdb/accessors_chain_indexes_test.go
- core/rawdb/accessors_chain_test.go
- core/rawdb/database.go
- core/rawdb/freezer.go
- core/rawdb/schema.go
- core/rawdb/table.go
- core/slice.go
- core/types/receipt.go
- ethdb/database.go
closes #1826 
Few points to consider on this pr
- HasHeader and HasBody
on the commits 6622c1d and 19eb146 I changed the hasBody and hasHeader keys to workobjects ones since they were not working properly, would this be the right way to solve this?
Functions are referenced on
HasHeader on [sliceAppend]( https://github.com/dominant-strategies/go-quai/blob/main/core/slice.go#L207)
HasBody on api [ImportChain](https://github.com/dominant-strategies/go-quai/blob/main/quai/api.go#L220)
-  ReadAllHashes functions is not working properly. 
It was supposed to read all hashes associated with a number.
Previously in order to write headers header key which had the headerPrefix and blockNumber and hash appended was used
but now workobjects write method only append by hash.
Now ReadAllHashes always …
> Accessor methods tests 2

- metrics_config/grafana_metrics.json
- metrics_config/metrics.go
- p2p/node/api.go
resolves: https://github.com/dominant-strategies/meta-repo/issues/264
> Propagation metrics

- p2p/node/peerManager/peerdb/datastore_test.go
Increase prefix length to avoid collision
> fix prefix test

- cmd/utils/flags.go
External repos that import go-quai don't have access to the viper backend. It doesn't crash but it can't interpret the default value. This sets the default value path explicitly.
> Fix default viper values for external repos (stratum)

- core/vm/evm.go
Fixes https://github.com/dominant-strategies/go-quai/issues/2032
> Bugfix: Precompile check only needs the location byte prefix in the first byte

- cmd/utils/flags.go
This enables the required RPCs for mining by default, which many are doing on the devnet. There is no security concern as the corsdomain is still local by default which blocks external connections.
> Enable WS and HTTP by default (limited to local)

- common/address.go
- core/state/statedb.go
- core/vm/instructions.go
Resolves https://github.com/dominant-strategies/go-quai/issues/1994
> Clean up address errors

- consensus/blake3pow/consensus.go
- consensus/blake3pow/poem.go
- consensus/blake3pow/sealer.go
- consensus/consensus.go
- consensus/progpow/consensus.go
- consensus/progpow/poem.go
- consensus/progpow/sealer.go
- core/worker.go
Requried for https://github.com/dominant-strategies/go-quai-stratum/issues/76
> Workshares changes for stratum

- Dockerfile
- common/bootnodes.go
The dns is already made in cloud flare. this makes it easier to change the bootnode ips without changing the source code.
> use dns for bootnodes instead of ip

- core/state/statedb.go
- core/state_transition.go
- core/vm/contracts.go
- core/vm/errors.go
- core/vm/evm.go
- core/vm/instructions.go
- core/vm/interface.go
- core/vm/operations_acl.go
- internal/quaiapi/api.go
- internal/quaiapi/quai_api.go
- internal/quaiapi/transaction_args.go
- quai/api_backend.go
- quai/quaiconfig/config.go
- quaiclient/ethclient/ethclient.go
An Access List is a set of addresses and storage keys that a transaction accesses in the EVM. The list must be provided with the transaction, and if the list is incomplete, the transaction will fail. Therefore a user who wants to send a transaction that uses the EVM must call quai_createAccessList and attach the returned access list to the transaction before signing and submitting. A transaction that does not use the EVM, such as a simple balance transfer, does **not** need to supply an Access List because the sender and receiver are already part of the transaction.
**This PR makes many changes to the EVM and requires a robust review and audit.**
> Enforce Access Lists

- core/state_processor.go
- core/tx_pool.go
- core/types/transaction.go
- core/worker.go
Also removed expired Qi txs from pool on a regular interval
> Allow Qi denom aggregation for first tx in block

- common/address.go
- core/types/transaction_marshalling.go
- core/types/wo.go
- internal/quaiapi/api.go
- internal/quaiapi/quai_api.go
Fixes https://github.com/dominant-strategies/go-quai/issues/2122
> Return MixedcaseAddress with proper checksum for RPC requests

- cmd/utils/flags.go
This flag was misinterpreted since it was opened. This flag is a true/false bool that used to indicate to the node whether it should act as a "server" in the kademlia DHT or not. Since the introduction of this flag we decided that all nodes should act as servers by default. Therefore this flag is now deprecated.
The "bootpeers" flag is still available and used.
> Remove unused bootnode bool flag

- internal/quaiapi/quai_api.go
- quai/api_backend.go
Resolves https://github.com/dominant-strategies/go-quai/issues/2177
> Fix rpc inconsistencies

- cmd/utils/cmd.go
- cmd/utils/flags.go
- quai/backend.go
- quai/filters/api.go
- quai/filters/filter_system_test.go
Resolves https://github.com/dominant-strategies/go-quai/issues/2184
> Configurable subscription limit

- core/block_validator.go
- core/tx_pool.go
- internal/quaiapi/api.go
- internal/quaiapi/quai_api.go
- quai/quaiconfig/config.go
- quaiclient/ethclient/ethclient.go
GasPrice API returns smallest units, EstimateGas returns higher estimate, EstimateFeeForQi works, higher fee cap
> API Bugfixes

- core/block_validator.go
- core/tx_pool.go
Resolves https://github.com/dominant-strategies/go-quai/issues/2225
> Reject blocks which emit Qi UTXOs to inactive chains

- core/state/statedb.go
- core/state_transition.go
- core/vm/interface.go
Resolves https://github.com/dominant-strategies/go-quai/issues/2265
> Bypass AccessList enforcement for ETXs

- core/slice.go
sl.NodeCtx() will not go wrong, and the return value is one of ZONE_CTX/REGION_CTX/PRIME_CTX, but the logic in the switch case is the same and can be removed
> feat: remove unnecessary code

- core/vm/instructions.go
Accesslist storage slot checks are not necessary for parallelization, rather just the address checks are necessary. And, in fact, it is virtually impossible to guarantee that a user will get a specific storage slot before the transaction confirms.
> Remove Access List Storage Slot Checks

- quai/p2p_backend.go
Initially noted by: https://github.com/dominant-strategies/go-quai/pull/2410
> bugfix: use MaxRegions variable for the region api backends

- core/state_processor.go
- core/worker.go
For the normal case, the ETX data will now be: 1 byte lockup byte, 32 byte workshare hash, for 33  bytes total. Pools will have to parse out the first byte of the data.
> Allow workshare hashes in coinbase ETX data

- core/rawdb/accessors_chain.go
- quai/backend.go
The new pr for https://github.com/dominant-strategies/go-quai/pull/2457
> refactor: using slices.Contains to simplify the code

- core/core.go
- core/tx_pool.go
- core/types/transaction.go
- core/worker.go
- internal/quaiapi/quai_api.go
- quai/api_backend.go
Rule: all transactions in a block must be sorted by ascending nonce and descending gas price.
We can have multiple txs for a given account in a block as long as this rule is followed. This PR makes the worker follow this (already enforced) rule when sorting transactions in the worker.
> Added tx filtering in worker so an account can have multiple txs per block

- consensus/progpow/algorithm_progpow.go
- consensus/progpow/consensus.go
- consensus/progpow/progpow.go
- consensus/progpow/sealer.go
This lookup cache was added 10 months back to save generating the data set item for a given index. But the index is not unique between epochs, so this cache introduces a bug where the progpow verification fails. As this didnt exist in the original go-ethereum or the progpow PR that was made to the ethereum, removing it is a safer option. The function to generate the dataset item is very simple and has some simple math operations and few keccack hashes. So time saved by introducing this is not enough to justify this code.
> bugfix: Removed the lookup cache for the data set item
