core/state/access_list.go
core/types/transaction.go

Will create an issue to investigate in the future if this affects anything wrt EVM

Access list - Fixed Method handler crashing due to nil Access List

---

consensus/errors.go
consensus/ethash/consensus.go
consensus/misc/verify_quai.go
core/genesis.go
core/types/block.go
params/config.go
params/protocol_params.go

Map context ontology expansion

---

core/blockchain.go
eth/api_backend.go
ethclient/ethclient.go
internal/ethapi/backend.go
internal/ethapi/quai_api.go
les/api_backend.go

Goes with https://github.com/spruce-solutions/quai-manager/pull/59

quai_api.go: updated reorg api for new and old headers

---

core/blockchain.go
eth/api_backend.go
ethclient/ethclient.go
internal/ethapi/backend.go
internal/ethapi/quai_api.go
les/api_backend.go

ethclient: Implemented GetHeadTd method which gives the TD of the latest Head in a chain

ethclient: Implemented GetHeadTd method

---

networkvisualizer/network_visualizer.go

Removed the old flag system and setup CLI framework for future flags.

networkvisualizer: setup CLI framework

---

networkvisualizer/network_visualizer.go

Changed to make reading uncles/bad blocks in the graph more intuitive.

networkvisualizer: Changed identifier prefix

---

ethstats/ethstats.go

The idea of this is just to bring the `reportLatency` method inline with the others regarding the format of the report on the `write` of the websocket. This allows the flow on `quai-stats-backend` to be more similar relative to the others. 
I wrote a utility bash script as follows which people might like, but it's excluded from the PR. I just made it so I could get everything up and down more easily to UAT locally:
```
#! /usr/bin/bash
FUNCTION="rs"
compile() {
echo -e $'\nCompiling...\n'
make go-quai
}
run_stats() {
echo -e '\nRunning stats...\n'
rm -rf ~/.quai
rm -rf nodelogs
make stop
make run-stats
}
help()
{
echo -e "\nHelper script to run go-quai utilities locally.\n"
echo "Syntax: scriptTemplate [-|h|c|rs]"
echo "options:"
echo "-c     Compile go-quai."
echo "-s    Run stats."
echo …
```

reformat latency to be inline with other reports

---

core/miner.go
core/worker.go

Removed exitCh in miner and put the exit logic into stopCh
since there is no need to have 2 channels to stop and exit
in the current scenario.
worker had a startCh and on start the miner was sending a
message in channel and it was never getting caught.

Bugfix: Fixed node not stopping because of startCh in worker

---

common/types.go

This patch implements a map of address prefixes, to map each address into a particular shard/chain within the network. Additionally, I provide the Name() & ContainsAddress(...) methods to facilitate address location checking.
This PR puts in some machinery necessary for address checking, but the actually address bounds will likely change, pending this issue: https://github.com/dominant-strategies/quai-specs/issues/24

Create address prefix map and associated methods

---

core/core.go
core/slice.go
eth/api_backend.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
quaiclient/quaiclient.go

This reverts commit fefda0be05464d45e4a47c8c1709625592e385ef.

Revert "Removed the PendingHeader as a return from slice"

---

consensus/blake3pow/consensus.go
consensus/consensus.go
consensus/misc/dao.go
core/block_validator.go
core/chain_makers.go
core/evm.go
core/genesis.go
core/state/statedb.go
core/state_processor.go
core/state_transition.go
core/tx_noncer.go
core/tx_pool.go
core/vm/eips.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/instructions.go
core/vm/interface.go
core/vm/interpreter.go
core/vm/logger.go
core/vm/operations_acl.go
core/vm/runtime/runtime.go
eth/api.go
internal/quaiapi/api.go
internal/quaiapi/quai_api.go

This PR restores a prior commit (already approved here: https://github.com/dominant-strategies/go-quai/pull/449) which got dropped out in a rebase error

Restore context checking in statedb

---

common/types.go
core/block_validator.go
core/state_processor.go
core/state_transition.go
core/types.go
core/types/transaction.go
core/types/transaction_marshalling.go
core/types/transaction_signing.go
core/vm/instructions.go
core/vm/jump_table.go
quaiclient/ethclient/ethclient.go

Also updated opETX to include proper gas calculation and balance subtraction in the origin.

Add ETX processing and validation

---

core/slice.go

This bug was introduced in ad9b6dfc.

bugfix: update only when location not equal in zone

---

core/slice.go
p2p/dial.go

Also increase loglevel for adding static peer and one spelling fix

Added peering info that prints out number of peers every ten seconds

---

core/types/external_tx.go
core/types/transaction_marshalling.go
core/vm/evm.go
core/vm/instructions.go

Add external transaction chain ID

---

params/bootnodes.go

Updated dnsPrefix to remove legacy les, all, etc.

---

core/core.go
core/miner.go
core/types/block.go
core/worker.go
eth/api_backend.go
eth/filters/api.go
eth/filters/filter.go
eth/filters/filter_system.go
internal/quaiapi/backend.go
quaiclient/ethclient/ethclient.go

Removed HeaderRoots Update subscription from worker

---

core/slice.go
core/types/block.go
core/types/hashing.go
core/worker.go

Resolves https://github.com/dominant-strategies/go-quai/issues/625

bugfix: Using All the RootHashes as the key to store the pendingBlockBody

---

core/core.go
core/types/timed_cache.go

Resolves https://github.com/dominant-strategies/go-quai/issues/542

Future headers should expire after a given time

---

.gitignore
core/slice.go

Resolves https://github.com/dominant-strategies/go-quai/issues/619

Backfill missing pending ETXs for a given block

---

core/types/block.go
core/worker.go

Resolves https://github.com/dominant-strategies/go-quai/issues/615

bugfix: Resume downloader after any successful insert

---

core/slice.go

This is a departure from the top-down picking originally proposed by HLCR. Only zones have sufficient information to make decisions in which block to keep mining.  The hierarchical constraint is now statistically enforced by setting subordinate Tds to dominant values on coincident blocks.  Note that this is a statistical enforcement and not a strict enforcement as previously proposed. This appears to create a much more robust head pick that never stalls or seperates.
Coordinate updates coerce the ph pick to the result of the coordinate coincident dom head choice.  The dom and its head choice is neccassarily the correct choice because the the dom is always shared.

Refactor of phCache and head picking to always choose the greatest Td in zones

---

eth/fetcher/block_fetcher.go
eth/handler.go

Now the transactions are propagated to the direct peers and they can mine the transactions

bugfix: Accept Transactions when at the Fray

---

Makefile

Closes https://github.com/dominant-strategies/go-quai/issues/675

Remove broken Make targets

---

.github/workflows/build-deploy.yml

fixed a bug that made commit messages ugly and another that makes them

---

p2p/discover/v4_udp.go

This PR updates the wire version from 4 to 18 and adds a check on received Pings to ensure the version matches. Ping requests from invalid versions are ignored.

Update wire to version 18 and add version check on ping

---

Makefile
network.env.dist

Closes https://github.com/dominant-strategies/go-quai/issues/689

Add syncmode to network.env

---

node/config.go

Closes https://github.com/dominant-strategies/go-quai/issues/690

Fixed version name in broadcast, be sure to update bootnodes

---

consensus/blake3pow/consensus.go

Resolves https://github.com/dominant-strategies/go-quai/issues/665

Enforce dom's difficulty is always greater than sub's difficulty

---

core/tx_pool.go
core/types/internal_tx.go
eth/handler.go

Accept transactions from peers on writeblock and send all transactions to all peers (including queued transactions)

Fix tx propagation

---

core/tx_pool.go
core/types/external_tx.go
core/types/internal_to_external_tx.go
core/types/internal_tx.go

Also better block gas limit error formatting (prints the actual block gas limit)

Fix transaction expected nil type for RPC

---

Makefile
eth/downloader/downloader.go
eth/downloader/peer.go
eth/handler_eth.go
eth/peer.go
eth/peerset.go
eth/protocols/eth/peer.go
eth/sync.go
network.env.dist
p2p/msgrate/msgrate.go
p2p/peer.go
quaistats/quaistats.go

Report peer stats and expose RTT information from peerset

---

core/rawdb/accessors_chain.go
core/state_processor.go

Resolves https://github.com/dominant-strategies/go-quai/issues/480

Improve EtxSet load/store performance

---

common/types.go

Resolves https://github.com/dominant-strategies/go-quai/issues/739

Helper function to translate from order number to string

---

.github/PULL_REQUEST_TEMPLATE.md

Resolves https://github.com/dominant-strategies/go-quai/issues/741

Automatically tag @core-dev for review in this repo

---

core/block_validator.go

bugfix: Don't collect ETX rollup in Prime validator

---

log/logger.go

@kiltsonfire requested this change

Changed logger to output time in UTC

---

Dockerfile
consensus/blake3pow/consensus.go

removed the knot from the Dockerfile

---

core/headerchain.go

bugfix: set commonHash to Genesis if nil

---

eth/protocols/eth/handshake.go
eth/protocols/eth/protocol.go

Added Location field to StatusPacket and checked in peer handshake

---

core/bodydb.go
core/core.go
core/genesis.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/database.go
core/rawdb/freezer.go
core/rawdb/table.go
core/slice.go
core/types/block.go
eth/api_backend.go
eth/downloader/downloader.go
eth/protocols/eth/handler.go
ethdb/database.go
internal/quaiapi/api.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
quaistats/quaistats.go

Only look at the last commit as this is rebased on Poem branch

Remove Total Difficulty and references to it from codebase, replaced with Entropy where necessary

---

cmd/utils/flags.go
common/address.go
consensus/blake3pow/consensus.go
core/chain_makers.go
core/core.go
core/evm.go
core/gen_genesis.go
core/genesis.go
core/state/dump.go
core/state_processor_test.go
core/state_transition.go
core/tx_pool.go
core/vm/eips.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/instructions.go
core/vm/logger.go
core/vm/operations_acl.go
core/vm/runtime/runtime.go
eth/api.go
eth/backend.go
internal/quaiapi/api.go
internal/quaiapi/quai_api.go

Refactor: InternalAddress returns a copy instead of a pointer

---

core/rawdb/accessors_chain.go
core/state_processor.go

This reverts commit e138c3f07c21e957e872672dae64ea0906fb9731.
This reverts commit 00a0ce7ee18f5328c0686efd567532c01b00ad7d.
This reverts commit b2b243a08b8d8f57feb2fece2966e2571b214ca8.

bugfix: Revert EtxSet load/store broken refactor

---

internal/quaiapi/quai_api.go

Added order as part of API response in rpcMarshalBlock

---

core/state_processor_test.go
core/tx_pool.go

Fix etx error log in tx pool and fix local genesis block

---

quaistats/quaistats.go

Set height to uint64

---

core/block_validator.go
core/bodydb.go
core/genesis.go
core/headerchain.go
core/slice.go
core/state_processor.go
core/tx_pool.go
core/types/block.go
eth/downloader/downloader.go
eth/protocols/eth/handlers.go
internal/quaiapi/api.go
params/bootnodes.go
params/config.go
params/protocol_params.go

Bugfix and updated gas limit for all networks

---

core/tx_pool.go

Increased tx pool limits

---

core/tx_pool.go

Update tx pool limits

---

core/slice.go

Improves performance from previous commit

Store timestamp once when picking pendingHeader

---

quaistats/quaistats.go

Removing txs from stats to avoid flooding outbound

---

consensus/blake3pow/consensus_test.go
consensus/blake3pow/difficulty.go
core/forkid/forkid_test.go
core/state_transition.go
core/vm/gas_table.go
core/vm/instructions.go
core/vm/jump_table.go
crypto/crypto.go
eth/handler_eth_test.go
params/protocol_params.go
tests/difficulty_test.go
tests/fuzzers/difficulty/difficulty-fuzz.go
tests/init.go
tests/transaction_test_util.go

Old PR: https://github.com/dominant-strategies/go-quai/pull/512
This PR builds on https://github.com/dominant-strategies/go-quai/pull/803

Remove all references to Frontier

---

cmd/go-quai/main.go
cmd/go-quai/usage.go
cmd/utils/flags.go
consensus/misc/eip1559_test.go
core/forkid/forkid_test.go
core/state/state_object.go
core/state/statedb.go
core/state_processor_test.go
core/types/hashing_test.go
core/types/transaction.go
core/types/transaction_marshalling.go
core/types/transaction_signing_test.go
core/vm/eips.go
core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go
core/worker.go
eth/api_backend.go
eth/backend.go
eth/handler_eth_test.go
internal/quaiapi/api.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
node/config.go
params/config.go
tests/difficulty_test.go
tests/init.go
tests/transaction_test_util.go

Old PR: https://github.com/dominant-strategies/go-quai/pull/513
This PR builds on https://github.com/dominant-strategies/go-quai/pull/804

Remove all references to Spurious Dragon hard fork and related EIPs

---

core/tx_pool.go
core/worker.go
eth/fetcher/tx_fetcher.go
eth/handler.go

Increase Tx fetcher limits

---

eth/fetcher/tx_fetcher.go

Change error log in tx fetcher to debug

---

quaistats/quaistats.go

New tps calculations

---

quaistats/quaistats.go

fixed logic bug around tps computation

---

core/slice.go
core/types/block.go
quaistats/quaistats.go

added append time calculation

---

core/slice.go
core/types/block.go
quaistats/quaistats.go

add stats:CPUUsage, RAMUsage, SwapUsage, DiskUsage

---

core/tx_pool.go
core/types/transaction.go
core/worker.go

Should reduce pending generation time. The worker grabs the pending list and etx list from the txpool and combines them, then grabs the first transaction for each account (by nonce) and sorts them by fee. Then for each transaction after that, the worker grabs the next transaction for each account (by nonce) and sorts the list by fee again. I have changed the logic to remove sorting.

Worker adds transactions without sorting and TxPoolPending grabs readlock

---

core/tx_pool.go
eth/protocols/eth/broadcast.go
eth/protocols/eth/peer.go

Update peer broadcast limits

---

core/slice.go
core/worker.go

Move generating the state root out of append

---

quaistats/quaistats.go

added calculation for mgas

---

quaistats/quaistats.go

quaistats.go -> fixed bug where avg gas was using wrong cache

---

core/bodydb.go
core/core.go
core/slice.go
core/worker.go
quaistats/quaistats.go

Report uncles to stats connor

---

core/bodydb.go
core/headerchain.go
core/slice.go
core/tx_pool.go

bugfix: Race condition if blocks are not in canonical db

---

consensus/misc/eip1559_test.go
core/state_processor_test.go
core/vm/runtime/runtime.go
params/config.go
tests/difficulty_test.go

The glacier was too big so we had to remove it.

Cleanup Muir Glacier

---

core/tx_pool.go

Reduce number of account slots in tx pool

---

core/bodydb.go
core/core.go
core/slice.go
core/worker.go
quaistats/quaistats.go

This reverts commit 00bdbef97095a7f3e280eb6adf9fa85be4c10c7e.

Revert "bugfix: send the uncles to chainSideFeed for recording"

---

consensus/misc/eip1559_test.go
core/state/statedb.go
core/state_processor_test.go
core/state_transition.go
core/tx_pool.go
core/types/block_test.go
core/types/hashing_test.go
core/types/receipt.go
core/types/transaction.go
core/types/transaction_test.go
core/vm/contracts.go
core/vm/contracts_test.go
core/vm/eips.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/jump_table.go
core/vm/operations_acl.go
core/vm/runtime/runtime.go
core/vm/runtime/runtime_test.go
eth/ethconfig/config.go
interfaces.go
internal/quaiapi/api.go
internal/quaiapi/quai_api.go
params/config.go
params/protocol_params.go
rlp/decode.go
rlp/raw.go
rlp/raw_test.go
tests/block_test.go
tests/init.go

Cleanup Berlin

---

core/slice.go

bugfix: Added lock and rlock around phCache access in relay

---

core/genesis.go
params/config.go
params/protocol_params.go

Updated the min gas limit to 15M and colosseum gas to 15M

---

quaistats/quaistats.go

bugfix: fullBackend was expecting deprecated .Miner()

---

core/genesis.go
core/headerchain.go
params/config.go

Changed gas in orchard to 25M

---

core/genesis.go
core/headerchain.go
params/config.go

Removed gas limit change

---

core/genesis.go
core/tx_pool.go
params/config.go
params/protocol_params.go

Minor fixes related to testing and Improved logging in Tx Pool

---

core/bodydb.go
core/core.go
core/slice.go
core/worker.go
quaistats/quaistats.go

This reverts commit 50fd2e04bbce9e95652b9d54485f7eb65d77537c.

Revert "Revert "bugfix: send the uncles to chainSideFeed for recording""

---

core/bodydb.go
core/chain_indexer.go
core/core.go
core/headerchain.go
core/miner.go
core/slice.go
core/tx_pool.go
eth/api_backend.go
eth/discovery.go
eth/downloader/peer.go
eth/filters/filter_system_test.go
eth/handler_eth_test.go
eth/handler_test.go
eth/protocols/eth/discovery.go
event/event_test.go
event/example_feed_test.go
event/example_scope_test.go
event/feed.go
event/feed_test.go
internal/quaiapi/backend.go
p2p/server.go
quaistats/quaistats.go

Make feed subscriptions optionally blocking

---

core/core.go
core/rawdb/accessors_chain.go
core/rawdb/schema.go
core/slice.go
core/types/block.go
eth/api_backend.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
quaiclient/quaiclient.go

Made it so pick ph only happens in zones

---

core/slice.go

bugfix: updatePhCache should be inslice update on relayPh

---

core/slice.go
eth/api_backend.go

bugfix: Returning error if block is nil, and set before send chain head

---

core/tx_pool.go

Time logging around txpool functions

---

core/bodydb.go
core/chain_indexer.go
core/core.go
core/headerchain.go
core/miner.go
core/slice.go
core/tx_pool.go
eth/api_backend.go
eth/discovery.go
eth/downloader/peer.go
eth/filters/filter_system_test.go
eth/handler_eth_test.go
eth/handler_test.go
eth/protocols/eth/discovery.go
event/event_test.go
event/example_feed_test.go
event/example_scope_test.go
event/feed.go
event/feed_test.go
internal/quaiapi/backend.go
p2p/server.go
quaistats/quaistats.go

This reverts commit a2b5099afbd1946c8baf319a9fea2e50587df423.

Revert "Make feed subscriptions optionally blocking"

---

eth/fetcher/tx_fetcher.go
eth/protocols/eth/broadcast.go
eth/protocols/eth/peer.go

Reduced peer tx limits, txfetcher limits, and maxTxPacketSize to original limits

---

core/core.go
core/miner.go
core/slice.go
core/worker.go
eth/api.go
eth/api_backend.go

Optimized worker to have only one Async Ph generation and cleanup

---

core/worker.go

Lowered the pending block body limit from 1024 to 32

---

core/types/etx_set.go

bugfix: Made the Update method on EtxSet to work with Pointer

---

consensus/blake3pow/blake3pow.go
log/logger.go
node/config.go
node/node.go
p2p/dial.go
p2p/discover/common.go
p2p/discover/v5_udp.go
p2p/dnsdisc/client.go
p2p/server.go

Enable real custom loggers

---

core/headerchain.go
core/slice.go

Fix crash when getting pEtx location from prime

---

core/tx_pool.go

Add warning if TX intrinsic gas is too low

---

core/types/block.go

Add hash cache to header

---

core/types/block.go

hotfix: Clear hash cache on header modification

---

core/evm.go
core/vm/evm.go

Bugfix: Return if sender address is not internal in Transfer

---

core/rawdb/accessors_chain.go
core/slice.go

bugfix: Initialize etxset on slice init

---

log/logger.go

Add milliseconds timestamp for debug level

---

core/worker.go

Remove unused tx subscriptions

---

log/logger.go

Increase log rollover limit and max backups

---

core/headerchain.go
core/worker.go

Keep cache of recent manifests

---

core/vm/instructions.go

Bugfix: opETX should validate gas price and tip from stack

---

core/genesis.go
params/config.go
params/protocol_params.go

Setting up for large scale galena test.

Change Galena target to 12s, 100x difficulty

---

params/bootnodes.go

updated bootnodes.go w/ new orchard enodes

---

core/slice.go

Moved composition of new worker states into updatePhCache, added a mutex aroudn updatePhCache, and logical branch to allow root updates

---

internal/quaiapi/api.go

Bugfix: EstimateGas should use latest block instead of worker pending block

---

core/blocks.go
core/core.go
core/error.go
core/rawdb/accessors_chain.go
core/rawdb/schema.go
core/slice.go
core/worker.go
eth/api_backend.go
eth/downloader/downloader.go
eth/fetcher/block_fetcher.go
eth/handler.go
eth/handler_eth.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
quaiclient/quaiclient.go

Recover the network from a bad state

---

cmd/utils/flags.go
eth/backend.go
eth/ethconfig/config.go

Moved pprof to main

---

consensus/progpow/consensus.go
core/types/block.go

Cache progpow hash

---

.gitignore

added epoch to .gitignore since progpow

---

core/types/block.go
core/types/gen_header_json.go

bugfix: Fixed the handling of location field in the RPC layer

---

.github/workflows/cut-minor-release.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-sandbox.yml

change prod release flow

---

helm/templates/_statefulset.yaml
helm/values.yaml

updated helm chart run command

---

helm/templates/_statefulset.yaml
helm/values.yaml

fbugfix helm -> fixed slices escape chars

---

helm/templates/_statefulset.yaml
helm/values.yaml

bugfix helm -> fixed slices escape chars

---

helm/templates/_ingress.yaml
helm/templates/_service.yaml

updated helm chart to open 303* on TCP as well

---

eth/downloader/queue.go
eth/protocols/eth/handlers.go

bugfix: Fixed the downloader in Prime

---

README.md

changed to trigger deploy

---

README.md

trigger pipeline once more

---

README.md

updated README to trigger release

---

eth/downloader/queue.go

bugfix: Correct value for the requiredHeaderFetch in Queue

---

core/genesis.go
params/config.go

up'd zone difficulty from 1000 -> 11000

---

cmd/utils/flags.go
helm/templates/_statefulset.yaml
log/logger.go

add console log flag

---

internal/quaiapi/api.go
internal/quaiapi/quai_api.go

bugfix: Fixed RPC GetBlockByHash/Number to return the etxs

---

helm/templates/statefulset.yaml

added taint tolerations and affinities in helm stateful set

---

consensus/consensus.go
consensus/progpow/consensus.go
consensus/progpow/sealer.go
core/types/block.go
core/types/gen_header_json.go

This PR includes necessary helper functions for Stratum implementation in our proxy. Removed the work done to implement GetWork because the secondary changes required aren't done yet.
https://github.com/dominant-strategies/go-quai/pull/997
Big shoutout to @gameofpointers who basically co-authored.

GPU Compatibility: Logic for Stratum

---

core/genesis.go
params/config.go

Difficulty adjustment for Orchard GPU Miners

---

cmd/utils/flags.go
params/config.go

Change local and colosseum genesis hashes

---

consensus/consensus.go

added Hashrate to consensus.Engine interface

---

params/bootnodes.go

Updated the Galena network enodes

---

core/state_processor.go

Bugfix: ETX should be read from EtxSet for processing

---

core/core.go
core/slice.go
eth/filters/api.go
eth/filters/filter_system.go
eth/handler.go
eth/peerset.go
params/bootnodes.go

Small bug-fixes made during past few weeks of consensus testing

---

core/block_validator.go
core/bodydb.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/rawdb/schema.go
core/slice.go
core/state_processor.go
core/worker.go
eth/api_backend.go

Process state for a block only if it gets picked to be mined

---

core/genesis.go
params/config.go
params/protocol_params.go

Confirmed or Updated All the genesis hashes to the correct values

---

.github/workflows/build-deploy.yml

remove deploy from workflow

---

rlp/decode_test.go

rlp: change expected type on test

---

core/types/transaction.go
core/worker.go

Worker sorting

---

.github/workflows/cut-minor-release.yml

bugfix: Removed the GH_PAT from the checkout action

---

.github/workflows/build-deploy.yml
.github/workflows/cut-minor-release.yml

add ssh key back in pipeline

---

.github/workflows/cut-minor-release.yml

updates values.yaml in main

---

common/types.go
common/types_test.go

Fix common tests

---

core/headerchain.go

Bugfix: Only stop state processor if it is running

---

core/genesis.go
params/config.go

Changed the colosseum genesis Hash for progpow for a new start

---

core/headerchain.go

Picking the stop crash fix from main

---

core/core.go

bugfix: Added lock around block writes to reduce memory pressure

---

consensus/blake3pow/consensus.go
consensus/misc/basefee.go
consensus/misc/rewards.go
consensus/progpow/consensus.go
eth/fetcher/block_fetcher.go
params/config.go
params/protocol_params.go

Testnet changes: DDos prevention in fetcher and Reward calc for testnet

---

core/core.go

Added the sync dependency

---

core/slice.go

bugfix: Set the time in pendingHeader before send

---

cmd/utils/flags.go
consensus/blake3pow/blake3pow.go
consensus/blake3pow/consensus.go
consensus/progpow/consensus.go
consensus/progpow/progpow.go
core/slice.go
eth/ethconfig/config.go

Setting the Min Difficutly based on the genesis block difficutly

---

core/slice.go
eth/ethconfig/config.go

bugfix: Setting MinDiff in config in progpow

---

p2p/nat/nat.go

Panic if upnp or natpmp is disabled

---

cmd/utils/flags.go
consensus/blake3pow/blake3pow.go
consensus/blake3pow/consensus.go
consensus/progpow/consensus.go
consensus/progpow/progpow.go
core/core.go
core/slice.go
eth/ethconfig/config.go

Setting Min Difficulty to Half of genesis difficulty and bugfix

---

Makefile
cmd/utils/flags.go
eth/backend.go
network.env.dist

This reverts commit 72116c05b997c3a394193ebc7f2dfb0e41c3c5ef.

Removed PProf server from the codebase

---

consensus/blake3pow/consensus.go
consensus/progpow/consensus.go

VerifyHeader verifies that the coinbase is in scope

---

network.env.dist

Restrict HTTP and WS connections

---

Makefile
network.env.dist

Added ENABLE_NAT flag to specify the EXT_IP that the node needs to use

---

p2p/nat/nat.go

Graceful shutdown if node is not reachable

---

network.env.dist

Add port forwarding options to network.env.dist

---

network.env.dist

Testnet Nonce and Dist Change to enable Stratum

---

cmd/go-quai/config.go
node/defaults.go

Disable NAT for local developmental network

---

Makefile

fix: change echo output in Makefile

---

p2p/discover/table.go

Kademlia fix

---

p2p/nat/nat.go

Fix UPnP error message typo

---

Makefile

Allow NAT back to the Makefile

---

Makefile

Add NAT flag back to the Makefile

---

core/core.go

bugfix: Fixed the normalHashList dynamic proc

---

p2p/nat/nat.go

Improve UPnP docs link

---

params/version.go

Fixed the versioning formatter

---

core/core.go
core/headerchain.go
core/slice.go
core/types/block.go
core/worker.go
eth/api_backend.go
eth/downloader/downloader.go
eth/downloader/peer.go
eth/fetcher/block_fetcher.go
eth/handler.go
eth/handler_eth.go
eth/protocols/eth/broadcast.go
eth/protocols/eth/handler.go
eth/protocols/eth/handlers.go
eth/protocols/eth/peer.go
eth/protocols/eth/protocol.go
eth/sync.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
quaiclient/quaiclient.go

Changes and bugfixes

---

core/core.go
core/headerchain.go
core/slice.go
core/types/block.go
core/worker.go
eth/api_backend.go
eth/downloader/downloader.go
eth/downloader/peer.go
eth/fetcher/block_fetcher.go
eth/handler.go
eth/handler_eth.go
eth/protocols/eth/broadcast.go
eth/protocols/eth/handler.go
eth/protocols/eth/handlers.go
eth/protocols/eth/peer.go
eth/protocols/eth/protocol.go
eth/sync.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
p2p/dial.go
p2p/nat/nat.go
quaiclient/quaiclient.go

v0.19 changes

---

core/core.go
core/slice.go

Improve logs during append in slice.go and core.go

---

core/slice.go

bugfix: guard on termini if its nil

---

core/core.go
core/headerchain.go
core/rawdb/accessors_chain.go
core/slice.go
core/tx_pool.go
core/worker.go
eth/sync.go

Updates to Colosseum for 0.19_rc

---

cmd/utils/flags.go

bugfix: Colosseum disco was using the garden genesis Hash

---

cmd/utils/flags.go
p2p/dnsdisc/client.go
p2p/dnsdisc/tree.go

`fix`: fix nil array check on disco urls

---

eth/fetcher/block_fetcher.go
eth/handler.go

Entropy based stale broadcast decision

---

cmd/utils/flags.go
core/bodydb.go
core/headerchain.go
eth/fetcher/block_fetcher.go
eth/handler.go
p2p/dnsdisc/client.go
p2p/dnsdisc/tree.go

V19 changes

---

Makefile
network.env.dist

Add user configurable max peers option to lighten node requirements

---

core/state_processor.go

bugfix: Writing the EtxSet using batch to avoid writing invalid etxsets

---

Makefile

Make max peers optional, clean Makefile

---

consensus/blake3pow/consensus.go
consensus/consensus.go
consensus/progpow/consensus.go
eth/fetcher/block_fetcher.go
eth/handler.go

Added a Difficulty check in Zone for stale broadcast

---

core/core.go

Modified the Append Queue parameters to optimize the RAM, and sync speed

---

core/core.go

Change prefetch on regions to 3 to prevent stutter during sync

---

core/core.go

Changed syncing threshold for the zone

---

Makefile

More specific makefile stop command

---

core/types/etx_set.go

Log whenever an ETX is expired

---

common/types.go
core/core.go
core/tx_pool.go
core/types/etx_set.go
eth/downloader/downloader.go
eth/fetcher/block_fetcher.go
eth/handler.go
eth/handler_eth.go
eth/protocols/eth/handlers.go
internal/quaiapi/quai_api.go
p2p/discover/table.go
quaiclient/quaiclient.go

Changes to v0.21 and sync target and stale block classification refactor

---

consensus/progpow/consensus.go

Return powhash along with error if failed

---

Makefile

bugfix: Match full command for pgrep alternate platforms

---

eth/sync.go

CPU over usage is fixed now

---

Makefile
eth/sync.go

Reverting the Make Stop change and Remove the sleep from handler

---

Makefile
eth/sync.go

Revert the Make stop change and CPU usage reduction by 99%

---

consensus/blake3pow/consensus.go
consensus/progpow/consensus.go
core/blocks.go
core/error.go
core/headerchain.go
core/slice.go
core/state_processor.go
core/worker.go

V0.23 release

---

common/types.go
p2p/discover/table.go

This reverts commit f6be96dae19b94f429336040f521f7d7f7228ca3.

Revert "Revert "Increase Kademlia bucket & table sizes""

---

eth/fetcher/block_fetcher.go
eth/handler_eth.go

bugfix: Only perform stale block classification in Zones

---

eth/fetcher/block_fetcher.go
eth/handler_eth.go

bugfix: prints on the stale block classification

---

eth/fetcher/block_fetcher.go

bugfix: Increase the maxAllowableEntropyDist to 3500

---

core/error.go
core/slice.go
eth/fetcher/block_fetcher.go
eth/handler_eth.go

V0.23 revert

---

core/state_processor.go
eth/fetcher/block_fetcher.go
eth/protocols/eth/protocol.go

Change protocol version number for Quai1 protocol and increased window on stale block

---

core/error.go
core/slice.go
core/state_processor.go
eth/fetcher/block_fetcher.go
eth/handler_eth.go
eth/protocols/eth/protocol.go

V0.23 change

---

core/headerchain.go
core/slice.go
core/types/block.go

Petx compute optimization and new stats changes

---

Makefile
cmd/go-quai/config.go
cmd/go-quai/main.go
cmd/go-quai/usage.go
cmd/utils/flags.go
core/slice.go
quaistats/quaistats.go

quaistats: Reworked the stats package in the client to send new stats

---

core/miner.go

Fixes bug where no extra data is included in headers

---

Makefile
network.env.dist

Adds option for custom database directory

---

quaistats/quaistats.go

Minor stats changes

---

quaistats/quaistats.go

Stats deadlock fix

---

core/chain_indexer.go

Change reorg error to warning

---

consensus/misc/rewards.go
core/state_processor.go
core/tx_pool.go
core/types/block.go
core/types/qi_tx.go
core/types/transaction.go
core/worker.go
internal/quaiapi/api.go

Added base fee enforcement and sorting by fee to Qi txs

---

common/stream_services.go

bugfix: modify msg payload to include length prefix

---

cmd/utils/cmd.go
cmd/utils/flags.go
common/types.go
p2p/node/api.go
p2p/node/events.go
p2p/peerManager/peerManager.go
p2p/peerManager/peerdb/counter.go
p2p/peerManager/peerdb/peerdb.go
quai/interface.go
quai/p2p_backend.go

Peering based on topics, Fix Downloading, Goroutine optimizations

---

p2p/node/p2p_services.go
p2p/requestManager/requestManager.go

Establish timeout for stale requests

---

core/rawdb/accessors_chain.go
p2p/node/api.go
p2p/node/p2p_services.go
p2p/peerManager/peerManager.go
p2p/protocol/handler.go

Performance Improvements and Misc Changes

---

core/slice.go
core/worker.go

Bugfix: Worker should commit to EtxSetHash

---

p2p/peerManager/peerManager.go
p2p/requestManager/requestManager.go
p2p/streamManager/streamManager.go

Stream improvements and bugfixes

---

core/evm.go
core/worker.go

Bugfix: Worker should still fill inbound ETXs even if fill is false

---

common/types.go
p2p/node/api.go
p2p/node/node.go

Makes caching work on different contexts

---

.gitignore
cmd/go-quai/start.go
cmd/utils/flags.go
go.mod
go.sum
pprof_tool/memsimple.sh
pprof_tool/pprof.sh

Enable Pprof

---

core/types/block.go
params/config.go

Fixing mining on progpow

---

core/worker.go

fix: carried pointer on delete utxo array

---

core/genesis.go
p2p/pubsubManager/gossipsub.go
p2p/pubsubManager/utils.go

This should merge after @gameofpointers PR

Topic genesis prefix

---

cmd/go-quai/start.go

bugfix: Only set consensus backend once

---

core/headerchain.go
params/protocol_params.go

Misc bugfixes

---

core/tx_pool.go
core/worker.go

Bugfix: addUtxoTx should only RLock mempool if necessary

---

common/big.go
consensus/blake3pow/consensus.go
consensus/progpow/consensus.go
core/rawdb/accessors_chain.go
core/state_processor.go
core/tx_pool.go
core/types/utxo_validate.go
core/types/wo.go
core/worker.go
quai/gasprice/feehistory.go

Note: We no longer pay for inclusion of uncles. This is because blocks that reference uncles get some of the weight of that uncle.

Add EVM coinbase transaction and add signature to coinbase

---

common/bootnodes.go

Replace existing bootnodes

---

p2p/peerManager/peerManager.go

Report peer db stats

---

.gitignore
cmd/utils/flags.go
common/common_metrics.go
common/stream_services.go
core/tx_pool.go
metrics_config/grafana_metrics.json
metrics_config/metrics.go
metrics_config/prometheus.yml
p2p/node/node_metrics.go
p2p/pb/proto_metrics.go
p2p/pb/proto_services.go
p2p/protocol/handler.go
p2p/protocol/protocol_metrics.go
p2p/streamManager/streamManager.go
p2p/streamManager/stream_manager_metrics.go

Goldenage metrics + prometheus + grafana configs

---

p2p/node/api.go
p2p/pubsubManager/gossipsub.go
p2p/pubsubManager/utils.go
p2p/requestManager/requestManager.go
quai/interface.go

Implement topic Unsubscribe()

---

p2p/node/api.go
p2p/node/node.go
p2p/node/p2p_services.go
p2p/node/stats.go
p2p/peerManager/peerManager.go
p2p/pubsubManager/utils.go

Implement DHT for peer discovery

---

core/types/external_tx.go
core/types/qi_tx.go
core/types/quai_tx.go
core/types/transaction.go

Remove unused tx.protected() methods

---

internal/quaiapi/quai_api.go

Using the prime terminus header in QuaiToQi for better conversion estimation. Note precision is probably pretty bad because of the min denomination, so I added an EstimateFeeForQi function to the RPC that takes in a transaction and returns amount of qits needed to pay for the base fee (gas * basefee)
https://github.com/dominant-strategies/go-quai/issues/1496

Add Qi Base Fee Estimation

---

core/state_processor.go
core/types/qi_tx.go
core/worker.go
internal/quaiapi/quai_api.go
internal/quaiapi/transaction_args.go

https://github.com/dominant-strategies/go-quai/issues/1643

Added ETX and Conversion gas estimation to CalculateQiTxGas

---

cmd/utils/hierarchical_coordinator.go
core/core.go
core/tx_pool.go
core/types/transaction.go
internal/quaiapi/backend.go
p2p/node/api.go
p2p/node/pubsubManager/gossipsub.go
p2p/node/pubsubManager/utils.go
p2p/pb/proto_services.go
quai/api_backend.go
quai/handler.go
quai/p2p_backend.go

https://github.com/dominant-strategies/go-quai/issues/1699

Drop locals if they exceed queue limit and batch transaction propagation

---

cmd/go-quai/send.go
cmd/go-quai/start.go
cmd/utils/hierarchical_coordinator.go
p2p/node/api.go
p2p/node/events.go
p2p/node/node.go
p2p/node/pubsubManager/gossipsub.go
p2p/node/stats.go

resolves: https://github.com/dominant-strategies/go-quai/issues/1364

Libp2p graceful shutdown

---

ethdb/dbtest/testsuite.go

Fix broken tests on ethdb and set coverage on
```
ok  	github.com/dominant-strategies/go-quai/ethdb/leveldb	0.017s	coverage: 17.7% of statements
ok  	github.com/dominant-strategies/go-quai/ethdb/memorydb	0.003s	coverage: 84.6% of statements
ok  	github.com/dominant-strategies/go-quai/ethdb/pebble	0.009s	coverage: 51.0% of statements
```

remove obsolete code and add missing functions - fix merge conflicts

---

quaiclient/ethclient/ethclient.go

resolves: https://github.com/dominant-strategies/go-quai/issues/1701

bugfix: Fix MixedCaseAddress errors in Ethclient

---

consensus/blake3pow/poem.go
consensus/progpow/poem.go

Resolves https://github.com/dominant-strategies/go-quai/issues/1598

Quo() -> Div()

---

p2p/node/api.go
p2p/node/node.go
p2p/node/peerManager/peerManager.go
p2p/node/peerManager/peerdb/datastore.go
p2p/node/pubsubManager/utils.go
p2p/node/streamManager/streamManager.go

Read random peers from the database based on the RequestDegree specified

---

p2p/node/streamManager/streamManager.go

Kill stream after too many errors

---

p2p/node/api.go
p2p/node/node.go
p2p/node/peerManager/peerManager.go
p2p/node/utils.go
p2p/protocol/interface.go

Bootstrap peers from PeerDB

---

metrics_config/grafana_metrics.json
quai/p2p_backend.go

Workshare ingress

---

cmd/utils/flags.go
params/config.go

resolves https://github.com/dominant-strategies/go-quai/issues/1842

Fix genesis hash mismatch

---

consensus/progpow/algorithm_progpow.go
consensus/progpow/consensus.go
consensus/progpow/progpow.go
consensus/progpow/sealer.go

ProgPow: Cache DAG lookups

---

cmd/utils/flags.go
cmd/utils/hierarchical_coordinator.go
consensus/blake3pow/blake3pow.go
consensus/progpow/progpow.go
log/logger.go
p2p/node/peerManager/peerManager.go
p2p/protocol/main_test.go

Log size flags

---

core/core.go
core/tx_pool.go
internal/quaiapi/api.go
internal/quaiapi/backend.go
quai/api_backend.go
quaiclient/ethclient/ethclient.go
quaiclient/quaiclient.go
quaistats/quaistats.go

Fixes https://github.com/dominant-strategies/go-quai/issues/1899

Add Qi pool size to txpool status API

---

core/types/transaction_marshalling.go

Bugfix: Transaction JSON marshalling for outputs

---

core/tx_pool.go
internal/quaiapi/quai_api.go
metrics_config/grafana_metrics.json
quai/p2p_backend.go

Tx propagation metrics

---

metrics_config/grafana_metrics.json
p2p/node/node.go
p2p/node/stats.go

resolves https://github.com/dominant-strategies/go-quai/issues/1762

Libp2p metrics

---

metrics_config/grafana_metrics.json

Closes https://github.com/dominant-strategies/go-quai/issues/1940

Look at this photografana

---

common/stream_services.go
common/stream_services_test.go
metrics_config/grafana_metrics.json
p2p/node/p2p_services.go
p2p/node/peerManager/peerManager.go
p2p/node/stats.go
p2p/node/streamManager/streamManager.go
p2p/protocol/handler.go
p2p/protocol/interface.go

resolves https://github.com/dominant-strategies/go-quai/issues/1939

Add request-response bandwidth reporting

---

core/core.go
core/evm.go
core/headerchain.go
core/state_processor.go
core/tx_pool.go
core/types/transaction.go
core/worker.go
internal/quaiapi/quai_api.go
quaiclient/ethclient/ethclient.go

Bugfixes: Min gas for conversion, tx pool and EVM bugfixes

---

core/tx_pool.go
core/types/transaction.go
core/types/transaction_marshalling.go
core/types/utxo.go
core/worker.go
internal/quaiapi/api.go
internal/quaiapi/quai_api.go

resolves: https://github.com/dominant-strategies/go-quai/issues/1904

Prevent revalidation of Qi txs in reorgs

---

internal/quaiapi/api.go

closes https://github.com/dominant-strategies/go-quai/issues/1981

Modified the transaction response to have the etx type information in the external transactions

---

cmd/go-quai/config.go
cmd/go-quai/start.go

Add config command

---

core/types/bloom9.go

Resolves https://github.com/dominant-strategies/go-quai/issues/1990

Increase bloom filter size to 10KB

---

metrics_config/grafana_metrics.json
quai/p2p_backend.go

Part of https://github.com/dominant-strategies/go-quai/issues/1896

Add tx counters by slice

---

consensus/progpow/algorithm.go

Dataset parents to 512

---

cmd/utils/flags.go
params/config.go

Add configuration options for HTTP and WS RPCs

---

p2p/node/api.go
p2p/node/p2p_services.go
p2p/node/peerManager/peerManager.go
p2p/protocol/handler.go
p2p/quality_scores.go
quai/interface.go
quai/p2p_backend.go

Resolves https://github.com/dominant-strategies/go-quai/issues/1950
Resolves https://github.com/dominant-strategies/go-quai/issues/1949

Flow control

---

core/tx_pool.go

Resolves https://github.com/dominant-strategies/go-quai/issues/1883

Fix queued:ratelimit meter

---

p2p/node/requestManager/requestManager_test.go

Request manager tests

---

cmd/utils/flags.go
consensus/blake3pow/blake3pow.go
consensus/blake3pow/poem.go
consensus/blake3pow/sealer.go
consensus/consensus.go
consensus/progpow/poem.go
consensus/progpow/progpow.go
consensus/progpow/sealer.go
core/core.go
core/types/wo.go
core/worker.go
go.mod
go.sum
internal/quaiapi/api.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
internal/quaiapi/tx_worker.go
quai/api_backend.go
quai/backend.go
quai/p2p_backend.go
quai/quaiconfig/config.go
quaiclient/ethclient/ethclient.go
quaiclient/quaiclient.go

Transaction -> SubWorkshare -> Workshare or TxPool

---

p2p/node/api.go
p2p/protocol/handler.go

Resolves: https://github.com/dominant-strategies/go-quai/issues/2118

Fix request rate tracker

---

quai/api_backend.go
quai/filters/api.go
quai/filters/filter.go

Resolves https://github.com/dominant-strategies/go-quai/issues/2013

Subscription service to detect address accesses

---

core/worker.go

This fixes a previously merged commit in main

[Bugfix] Prevent worker from unintentionally double-spending UTXOs

---

metrics_config/grafana_metrics.json

This was deployed on garden but not merged yet into main
Closes #2168

Fix rates to work with metrics gauges

---

internal/quaiapi/api.go

Resolves https://github.com/dominant-strategies/go-quai/issues/2073

getTransactionByHash should return null if not found

---

consensus/blake3pow/consensus.go
consensus/consensus.go
consensus/progpow/consensus.go
core/core.go
core/headerchain.go
core/slice.go
core/worker.go
internal/quaiapi/backend.go
params/protocol_params.go
quai/api_backend.go

Computing Expansion Number retro actively to have it deterministic on

---

core/core.go
core/headerchain.go
core/state_processor.go
core/tx_pool.go
core/worker.go
internal/quaiapi/backend.go
internal/quaiapi/quai_api.go
params/protocol_params.go
quai/api_backend.go
quai/quaiconfig/config.go

Min base fee will be 5 Qits converted to Quai at the parent block rate
Max base fee will be a rolling average of the past 100 blocks calculated at the parent blocks rate

Added a min and max base fee

---

core/state_processor.go
core/types/qi_tx.go
core/types/utxo.go
core/types/wo.go
core/worker.go
internal/quaiapi/quai_api.go
quaiclient/ethclient/ethclient.go

CheckDenominations() does not work with 0.25 Qi and 50 Qi so those denominations have been temporarily removed.

New genallocs, removed 2 denominations to fix CheckDenominations() and bugfixes

---

p2p/node/api.go

Resolves https://github.com/dominant-strategies/go-quai/issues/1331

Fix peer timeout penalty

---

common/types.go
core/bodydb.go
core/core.go
core/events.go
core/headerchain.go
core/state_processor.go
core/worker.go
quai/api_backend.go
quai/filters/api.go
quai/filters/filter.go
quai/filters/filter_system.go
quai/filters/filter_system_test.go

Resolves https://github.com/dominant-strategies/go-quai/issues/2257

Generate access event on unlock

---

consensus/blake3pow/sealer.go
consensus/progpow/consensus.go
core/bloombits/matcher.go
quaiclient/quaiclient.go

Resolves https://github.com/dominant-strategies/go-quai/issues/2320
Resolves https://github.com/dominant-strategies/go-quai/issues/2325

Misc fixes

---

cmd/utils/flags.go
consensus/blake3pow/consensus.go
consensus/blake3pow/poem.go
consensus/blake3pow/sealer.go
consensus/misc/rewards.go
consensus/misc/statefee.go
consensus/progpow/consensus.go
consensus/progpow/poem.go
consensus/progpow/sealer.go
core/block_validator.go
core/chain_indexer.go
core/evm.go
core/headerchain.go
core/state_processor.go
core/types/utxo.go
core/worker.go
p2p/node/p2p_services.go
params/protocol_params.go

I intentionally left MinGasLimit to take in a block number so that it's easier to upgrade in the future.
It also now accepts prime number rather than zone.

Remove all forking logic from main

---

params/protocol_params.go
params/protocol_params_test.go

Modifying the state price to have an exponential cost based on the

---

trie/trie.go

Resolves https://github.com/dominant-strategies/go-quai/issues/818

Fix CVE-2021-41173

---

cmd/utils/flags.go
core/genesis.go
params/config.go
quai/backend.go
quai/quaiconfig/config.go

Resolves https://github.com/dominant-strategies/go-quai/issues/2448

Split genesisNonce into nonce+extra

---

core/state/state_object.go
core/state/statedb.go
core/state_processor.go

Resolves https://github.com/dominant-strategies/go-quai/issues/523

Fix finalise->finalize typos

---

quai/quaiconfig/config.go

Remove GenesisAllocs print that spams the logs on startup

---

quai/filters/api.go
quai/filters/filter.go
quai/filters/filter_system.go

Remove log limit - Orchard
